version: "3.9"
services:
  service-client:
    build:
      context: $PWD/Clientservice/
    ports:
      - "8080:8080"
    networks:
      - springm2_shared
  service-degradation:
    build:
      context: $PWD/degradationservice/
    ports:
      - "8081:8081"
    networks:
      - springm2_shared
  service-oauth:
    build:
      context: $PWD/oauth/
    ports:
      - "9191:9191"
    networks:
      - springm2_shared
networks: 
  springm2_shared:
    external: true 
