server:
  port: 8080

spring:
  application:
    name: clientService
  datasource:
    initialization-mode: always
    username: postgres
    password: client
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  cloud:
    consul:
      host: localhost
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        hostname: localhost
        register-health-check: false

---
spring:
  datasource:
    url: jdbc:postgresql://postgres-client:5432/client
    username: postgres
    password: client
  cloud:
    consul:
      host: consul
      discovery:
        hostname: clientService
        instance-id: ${spring.application.name}:instance_${random.value}
        prefer-ip-address: true
  config:
    activate:
      on-profile: docker
