server:
  port: 8080

spring:
  application:
    name: clientService
  config:
    name: clientService
  datasource:
    initialization-mode: always
    username: postgres
    password: client
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  cloud:
    consul:
      host: localhost
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        hostname: localhost
        register-health-check: false
