server:
  port: 8081

spring:
  application:
    name: degradationService
  datasource:
    initialization-mode: always
    username: postgres
    password: degrad
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/degrad
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  cloud:
    consul:
      host: localhost
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        hostname: localhost
        register-health-check: false
security:
  oauth2:
    resource:
      jwt:
        key-value: befezbfeHBdeedqjced768768
---
spring:
  datasource:
    url: jdbc:postgresql://postgres-degradation:5432/degrad
    username: postgres
    password: degrad
  cloud:
    consul:
      host: consul
      discovery:
        hostname: degradationService
        instance-id: ${spring.application.name}:instance_${random.value}
        prefer-ip-address: true
  config:
    activate:
      on-profile: docker
